<?php
/**
 * @var Safecharge_Safecharge_Block_Payment_Redirect_Form $this
 */
?>

<form name="safecharge_redirect"
      id="safecharge_redirect"
      action="<?php echo $this->getUrl(); ?>"
      method="POST">
      <?php echo $this->getInputs(); ?>
</form>
<script type="text/javascript">
    window.onload = function() {
        setTimeout(function() { submitForm(); }, 100);
        function submitForm() {
            document.getElementById("safecharge_redirect").submit();
        }
    }
</script>
