<?php
/**
 * @var Safecharge_Safecharge_Block_Form_Cc $this
 */
?>
<?php $_code = $this->getMethodCode() ?>

<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_type"><?php echo Mage::helper('payment')->__('Credit Card Type') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_cc_type"
                    name="payment[cc_type]"
                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Credit Card Type')) ?>"
                    class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName) : ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode == $_ccType) : ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>

    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
            <input type="text"
                   id="<?php echo $_code ?>_cc_number"
                   name="payment[cc_number]"
                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Credit Card Number')) ?>"
                   class="input-text validate-cc-number validate-cc-type required-entry"
                   value=""
            />
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="month validate-cc-exp required-entry">

            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k => $v) : ?>
                <option value="<?php echo $k ?$k : '' ?>"<?php if($k == $_ccExpMonth) : ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>

            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="year required-entry">
            <?php foreach ($this->getCcYears() as $k => $v) : ?>
                <option value="<?php echo $k ? $k : '' ?>"<?php if($k == $_ccExpYear) : ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
                </select>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
            <input type="text"
                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Name on Card')) ?>"
                   class="input-text required-entry"
                   id="<?php echo $_code ?>_cc_owner"
                   name="payment[cc_owner]"
                   value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>"
            />
        </div>
    </li>

    <?php echo $this->getChildHtml() ?>

    <?php if($this->hasVerification()) : ?>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
            <input type="text"
                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number')) ?>"
                   class="input-text cvv required-entry validate-cc-cvn"
                   id="<?php echo $_code ?>_cc_cid"
                   name="payment[cc_cid]"
                   value=""
            />
        </div>
    </li>
    <?php endif; ?>
</ul>